FROM fedora:26

RUN dnf -y update && dnf clean all && dnf -y install \
    python-pip \
 && dnf clean all

RUN pip install --upgrade setuptools && pip install ansible

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
