FROM centos:7

RUN yum update -y && yum clean all \
 && yum install -y epel-release && yum clean all \
 && yum install -y \
    python-pip \
 && yum clean all

RUN pip install --upgrade setuptools && pip install ansible

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
