FROM centos:6

RUN yum -y update && yum -y install epel-release && yum clean all \
 && yum -y install \
    gcc \
    libffi-devel \
    openssl-devel \
    python-devel \
    python-pip \
    upstart \
 && yum clean all

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools && pip install ansible

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
